src/pipelined_cpu_modular/common/mux2.v
src/pipelined_cpu_modular/common/mux3.v
src/pipelined_cpu_modular/common/flop_en_clr.v
src/pipelined_cpu_modular/controller/aludec.v
src/pipelined_cpu_modular/controller/maindec.v
src/pipelined_cpu_modular/controller/controller.v
src/pipelined_cpu_modular/register_file/reg_file_async.v
src/pipelined_cpu_modular/immediate/extend.v
src/pipelined_cpu_modular/alu/alu.v
src/pipelined_cpu_modular/branch/branch_logic.v
src/pipelined_cpu_modular/branch/next_pc_logic.v
src/pipelined_cpu_modular/memory_access/BE_logic.v
src/pipelined_cpu_modular/memory_access/register_write_data_logic.v
src/pipelined_cpu_modular/pipeline_reg/if_id_reg.v
src/pipelined_cpu_modular/pipeline_reg/id_ex_reg.v
src/pipelined_cpu_modular/pipeline_reg/ex_mem_reg.v
src/pipelined_cpu_modular/pipeline_reg/mem_wb_reg.v
src/pipelined_cpu_modular/hazard/forwarding_unit.v
src/pipelined_cpu_modular/hazard/hazard_detection_unit.v
src/pipelined_cpu_modular/hazard/flush_control.v
src/pipelined_cpu_modular/datapath.v
src/pipelined_cpu_modular/rv32i_pipeline_cpu.v
sim/verilator/tb_rv32i_load_use.cpp
